apiVersion: apps/v1
kind: Deployment
metadata:
  name: communications-server-prod
  namespace: communications-server-prod
  labels:
    app: communications-server-prod
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: communications-server-prod
  template:
    metadata:
      labels:
        app: communications-server-prod
    spec:
      imagePullSecrets:
      - name: registrysecret
      #serviceAccountName: communications-server-sa
      containers:
        - name: communicationsserverprod
          image: cooeyhub.azurecr.io/communications-server:5549
          imagePullPolicy: "Always"
          args: []
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "stage"
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: {{ .Values.requestMemory }}
              cpu: {{ .Values.requestCPU }}
            limits:
              memory: {{ .Values.limitMemory }}
              cpu: {{ .Values.limitCPU }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: communications-server-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1 
    name: communications-server-prod
    kind: Deployment 
  minReplicas: {{ .Values.minReplicas }}
  maxReplicas: {{ .Values.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75
---
