apiVersion: apps/v1
kind: Deployment
metadata:
  name: redox-worker-stage
  namespace: redox-worker-stage
  labels:
    app: redox-worker-stage
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: redox-worker-stage
  template:
    metadata:
      labels:
        app: redox-worker-stage
    spec:
      imagePullSecrets:
      - name: registrysecret
      serviceAccountName: redox-sa
      containers:
        - name: redoxworkerstage
          image: cooeyhub.azurecr.io/redox_worker:5689
          imagePullPolicy: "Always"
          args: []
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "stage"
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: {{ .Values.requestMemory }}
              cpu: {{ .Values.requestCPU }}
            limits:
              memory: {{ .Values.limitMemory }}
              cpu: {{ .Values.limitCPU }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: redox-worker-stage-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1 
    name: redox-worker-stage
    kind: Deployment 
  minReplicas: {{ .Values.minReplicas }}
  maxReplicas: {{ .Values.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75
---
