apiVersion: apps/v1
kind: Deployment
metadata:
  name: reports-worker-stage
  namespace: reports-worker-stage
  labels:
    app: reports-worker-stage
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: reports-worker-stage
  template:
    metadata:
      labels:
        app: reports-worker-stage
    spec:
      imagePullSecrets:
      - name: registrysecret
      serviceAccountName: report-sa
      containers:
        - name: reportsworkerstage
          image: cooeyhub.azurecr.io/reports-worker:5521
          imagePullPolicy: "Always"
          args: []
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "stage"
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: {{ .Values.requestMemory }}
              cpu: {{ .Values.requestCPU }}
            limits:
              memory: {{ .Values.limitMemory }}
              cpu: {{ .Values.limitCPU }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: reports-worker-stage-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1 
    name: reports-worker-stage
    kind: Deployment 
  minReplicas: {{ .Values.minReplicas }}
  maxReplicas: {{ .Values.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75
---
